#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x9C29BC560041E930 (jeff@bitprophet.org)
#
Name     : alabaster
Version  : 0.7.10
Release  : 1
URL      : http://pypi.debian.net/alabaster/alabaster-0.7.10.tar.gz
Source0  : http://pypi.debian.net/alabaster/alabaster-0.7.10.tar.gz
Source99 : http://pypi.debian.net/alabaster/alabaster-0.7.10.tar.gz.asc
Summary  : A configurable sidebar-enabled Sphinx theme
Group    : Development/Tools
License  : BSD-3-Clause
Requires: alabaster-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
What is Alabaster?
==================
Alabaster is a visually (c)lean, responsive, configurable theme for the `Sphinx
<http://sphinx-doc.org>`_ documentation system. It is Python 2+3 compatible.

%package python
Summary: python components for the alabaster package.
Group: Default

%description python
python components for the alabaster package.


%prep
%setup -q -n alabaster-0.7.10

%build
export LANG=C
export SOURCE_DATE_EPOCH=1488569061
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1488569061
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
